version: '3.1'

volumes: 
    dados:

networks: 
    banco:

services:
    db:
        image: postgres:latest
        volumes:
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts/db:/scripts/db
            - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/db/init.sql
        networks: 
            - banco
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db   
        ports: 
            - 5432:5432     